# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0031d04ce8a808742d2cbcc9955254ea933c77431f5f39231309d1ce27faa6dcba7c5e4ebf734b39a7b921a59f68ccaf6ca9f0f8abe708dcb6e304bf923fec23

test:
  secret_key_base: 98943d43acdc4fc6be2dd285e94d973a2d345317169e4c6a923750d5379428c0143ea0d2657d05b96b5ed30a9ce71ed7308443b5a078d1aa7548e96d0b1d9c16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
